--- #YAML:1.0
name:               DBD-cubrid
version:            9.1.0.0001
abstract:           CUBRID database driver for the DBI module
author:
    - Zhang Hui (zhanghui@nhn.com)
license:            perl
distribution_type:  module
configure_requires:
    DBI:                  1.61
    ExtUtils::MakeMaker:  0
build_requires:
    DBI:                  1.61
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    DBI:  1.61
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
